- name: ensure necessary directories are created
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "/usr/local/lib/systemd/resolved.conf.d" }
  tags: configs

# resolved_custom.conf.j2 is needed for annoying issue where disconnecting from VPN breaks local DNS routing
- name: install config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {
        src: "sudoers_custom.j2",
        dest: "/etc/sudoers.d/sudoers_custom",
        owner: "root",
        group: "root",
        mode: "0660",
      }
    - {
        src: "resolved_custom.conf.j2",
        dest: "/usr/local/lib/systemd/resolved.conf.d/custom.conf",
        owner: "root",
        group: "root",
        mode: "0644",
      }
  notify:
    - restart systemd-resolved
  tags: configs

- name: zoom tasks
  block:
    - name: check if zoom is installed
      stat:
        path: /usr/bin/zoom
      register: zoom

    - name: download zoom
      get_url:
        url: https://zoom.us/client/latest/zoom_x86_64.rpm
        dest: /tmp/zoom_x86_64.rpm
        mode: 0440
      when: zoom.stat.exists == False

    - name: install zoom
      dnf:
        name: /tmp/zoom_x86_64.rpm
        state: present
        disable_gpg_check: True
      when: zoom.stat.exists == False
  tags: zoom
