---
- name: install necessary packages
  package:
    name: [
    "autofs"
    ]
    state: present
  tags: packages

- name: install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    channel: "{{ item.channel }}"
  loop:
    - { name: "authy", classic: False, channel: "beta"}
  tags: snaps


- name: ensure necessary directories are created
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "/cifs" }
    - { path: "/usr/local/lib/systemd/resolved.conf.d" }
  tags: configs

# resolved_custom.conf.j2 is needed for annoying issue where disconnecting from VPN breaks local DNS routing
- name: install config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "sudoers_custom.j2", dest: "/etc/sudoers.d/sudoers_custom", owner: "root", group: "root", mode: "0660" }
    - { src: "resolved_custom.conf.j2", dest: "/usr/local/lib/systemd/resolved.conf.d/custom.conf", owner: "root", group: "root", mode: "0644" }
    - { src: "emacs.j2", dest: "/home/{{ user }}/.emacs", owner: "{{ user }}", group: "{{ user }}", mode: "0644" }
    - { src: "custom.autofs.j2", dest: "/etc/auto.master.d/custom.autofs", owner: "root", group: "root", mode: "0755" }
  notify:
    - restart autofs
    - restart systemd-resolved
  tags: configs

- name: create necessary symlinks
  file:
    src: "{{ share_path }}"
    dest: "/home/{{ user }}/readyshare"
    state: link
    force: True

- name: start and enable services
  service:
    name: autofs
    state: started
    enabled: True

- name: VPN tasks
  block:
    - name: check if VPN installed
      stat:
        path: /usr/bin/nordvpn
      register: vpn

    - name: download VPN script
      get_url:
        url: https://downloads.nordcdn.com/apps/linux/install.sh
        dest: /tmp/install.sh
        mode: '555'
      when: vpn.stat.exists == False

    - name: install VPN
      command: /tmp/install.sh -n
      when: vpn.stat.exists == False
  tags: vpn

- name: zoom tasks
  block:
    - name: check if zoom is installed
      stat:
        path: /usr/bin/zoom
      register: zoom

    - name: download zoom
      get_url:
        url: https://zoom.us/client/latest/zoom_x86_64.rpm
        dest: /tmp/zoom_x86_64.rpm
        mode: 0440
      when: zoom.stat.exists == False

    - name: install zoom
      dnf:
        name: /tmp/zoom_x86_64.rpm
        state: present
        disable_gpg_check: True
      when: zoom.stat.exists == False
  tags: zoom