---
- name: install necessary packages
  package:
    name: [
    "autofs",
    "cifs-utils",
    "samba-client"
    ]
    state: present
  tags: packages

- name: install config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "custom.autofs.j2", dest: "/etc/auto.master.d/custom.autofs", owner: "root", group: "root", mode: "0755" }
  notify:
    - restart autofs
  tags: configs

- name: create necessary symlinks
  file:
    src: "{{ share_path }}"
    dest: "/home/{{ user }}/readyshare"
    state: link
    force: True
    follow: False

- name: ensure necessary directories are created
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "/cifs" }
  tags: configs

- name: start and enable services
  service:
    name: autofs
    state: started
    enabled: True
