# Ansible Managed
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# Different bash prompts

PS1='\[\e[0;32m\]\u@\h\[\e[m\] : \[\e[1;34m\]\w\[\e[m\] ($(parse_git_branch))\[\e[1;32m\] \D{%F %T} \n\$\[\e[m\] \[\e[1;37m\]'
export PATH=$PATH:/usr/local/go/bin

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

#============================================================
#  Exports
#============================================================
export AOC_GO_CONFIG_DIR=$HOME/git/misc/advent_of_code_2020/config

#============================================================
#  Aliases
#============================================================

alias sudo="sudo "

alias diffdir="diff -bur"

alias enw="emacs -nw"

alias svim="sudo vim"

alias suspend='systemctl suspend'

alias podman-run-mariadb='podman run --name my-mariadb -e MYSQL_ROOT_PASSWORD=12345 -e MYSQL_USER=username -e MYSQL_PASSWORD=12345 -e MYSQL_DATABASE=dbname -p 3306:3306 -d mariadb'

#============================================================
#  FUNCTIONS
#============================================================

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

function docker-bash() {
    docker exec -it $1 /bin/bash
}
 
function bgNoOutput() {
    $1 > /dev/null 2>&1 & 
}
 
function recat() {

    for var in "$@"

    do

        if [ -f $var ]; then

            line=$(tail -n 1 $var)

            if [ "$line" != "" ]; then

                { cat $var; printf "\n"; } > $var.new

                mv $var{.new,}

            fi

        else

            ehco "SKIPPING: $var is not a file"

        fi

        cat $var

    done

}

# Go up to named directory
upto ()

{

    if [ -z "$1" ]; then

        return

    fi

    local upto=$1

    cd "${PWD/\/$upto\/*//$upto}"

}

# Complete dir names for upto
_upto()

{

    local cur=${COMP_WORDS[COMP_CWORD]}

    local d=${PWD//\//\ }

    COMPREPLY=( $( compgen -W "$d" -- "$cur" ) )

}

complete -F _upto upto

# Add a time stamp to the history format

export HISTTIMEFORMAT='%F %T '

 

 

#============================================================
#  COLOR FOR MAN PAGES
#============================================================

 

export LESS_TERMCAP_mb=$'\E[01;31m'

export LESS_TERMCAP_md=$'\E[01;31m'

export LESS_TERMCAP_me=$'\E[0m'

export LESS_TERMCAP_se=$'\E[0m'

export LESS_TERMCAP_so=$'\E[01;44;33m'

export LESS_TERMCAP_ue=$'\E[0m'

export LESS_TERMCAP_us=$'\E[01;32m'


#============================================================
#  OTHER
#============================================================

# Stuff that should only be done in an interactive shell (otherwise sftp/scp could break)

# Bash completions after sudo

complete -cf sudo

# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/__tabtab.bash ] && . ~/.config/tabtab/__tabtab.bash || true
