---
- name: install and enable chrome repos
  dnf:
    name: google-chrome-stable
    enablerepo: google-chrome

- name: install necessary packages
  package:
    name:
      [
        "terminator",
        "git",
        "fedora-workstation-repositories",
        "snapd",
        "firefox",
        "npm",
        "pipenv",
        "dnf-plugins-core",
        "gnome-tweaks",
        "google-chrome-stable",
      ]
    state: present
  tags: packages

- name: create necessary symlinks
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  loop:
    - { name: "postman", classic: False }
    - { name: "code", classic: True }
    - { name: "kotlin", classic: True }
    - { name: "spotify", classic: False }
  tags: snaps

- name: AWS CLI tasks
  block:
    - name: check if AWS CLI is already installed
      stat:
        path: /usr/local/aws-cli
      register: aws_cli

    - name: download latest AWS CLI
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes
      when: not aws_cli.stat.exists

    - name: install the AWS CLI
      command: /tmp/aws/install
      when: not aws_cli.stat.exists
  tags: aws-cli

- name: install and configure docker
  block:
    - name: install the docker repository
      command: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: install docker packages
      package:
        name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: installed

    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: True

    - name: add user to docker group
      user:
        name: "{{ my_user }}"
        groups: docker
        append: True

    - name: install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"
  tags: docker

- name: install config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    mode: 0644
  loop:
    - { src: "bashrc", dest: "/home/{{ my_user }}/.bashrc" }
    - {
        src: "terminator_config",
        dest: "/home/{{ my_user }}/.config/terminator/config",
      }
  tags: configs

- name: install custom sysctl config
  template:
    src: 99-custom.conf.j2
    dest: /etc/sysctl.d/99-custom.conf
    owner: root
    group: root
    mode: 0644
  tags: sysctl
  notify:
    - reload sysctl

- name: Git clone zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ my_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become_user: "{{ my_user }}"
  tags: zsh-autosuggestions
